services:
  db:
    image: mysql:8.0.39
    container_name: mysql-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: MyMovieList
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "${DB_PORT:-3306}:3306"

  api:
    build: .
    container_name: server
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db
    ports:
      - "7776:7776"