services:
  db:
    image: mysql:8.0.39
    container_name: mysql-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME:-MyMovieList}
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  api:
    build: .
    container_name: server
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: 123
      DB_PORT: 3306
    ports:
      - "7776:7776"