-- MySQL Script generated by MySQL Workbench
-- Fri Mar 14 17:45:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MyMovieList
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MyMovieList
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MyMovieList` DEFAULT CHARACTER SET utf8 ;
USE `MyMovieList` ;

-- -----------------------------------------------------
-- Table `MyMovieList`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyMovieList`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `password_salt` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idUser_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyMovieList`.`list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyMovieList`.`list` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_list_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_list_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `MyMovieList`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyMovieList`.`multimedia_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyMovieList`.`multimedia_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyMovieList`.`multimedia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyMovieList`.`multimedia` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `id_api` INT UNSIGNED NOT NULL,
  `multimedia_type_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_multimedia_multimedia_type1_idx` (`multimedia_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_multimedia_multimedia_type1`
    FOREIGN KEY (`multimedia_type_id`)
    REFERENCES `MyMovieList`.`multimedia_type` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyMovieList`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyMovieList`.`status` (
  `id` INT NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MyMovieList`.`list_has_multimedia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyMovieList`.`list_has_multimedia` (
  `list_id` INT UNSIGNED NOT NULL,
  `multimedia_id` INT UNSIGNED NOT NULL,
  `status_id` INT NULL,
  PRIMARY KEY (`list_id`, `multimedia_id`),
  INDEX `fk_list_has_multimedia_multimedia1_idx` (`multimedia_id` ASC) VISIBLE,
  INDEX `fk_list_has_multimedia_list1_idx` (`list_id` ASC) VISIBLE,
  INDEX `fk_list_has_multimedia_status1_idx` (`status_id` ASC) VISIBLE,
  CONSTRAINT `fk_list_has_multimedia_list1`
    FOREIGN KEY (`list_id`)
    REFERENCES `MyMovieList`.`list` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_list_has_multimedia_multimedia1`
    FOREIGN KEY (`multimedia_id`)
    REFERENCES `MyMovieList`.`multimedia` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_list_has_multimedia_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `MyMovieList`.`status` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `MyMovieList`.`multimedia_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `MyMovieList`;
INSERT INTO `MyMovieList`.`multimedia_type` (`id`, `name`) VALUES (1, 'MOVIE');
INSERT INTO `MyMovieList`.`multimedia_type` (`id`, `name`) VALUES (2, 'TV_SHOW');

COMMIT;


-- -----------------------------------------------------
-- Data for table `MyMovieList`.`status`
-- -----------------------------------------------------
START TRANSACTION;
USE `MyMovieList`;
INSERT INTO `MyMovieList`.`status` (`id`, `name`) VALUES (1, 'FINISHED');
INSERT INTO `MyMovieList`.`status` (`id`, `name`) VALUES (2, 'ON_HOLD');
INSERT INTO `MyMovieList`.`status` (`id`, `name`) VALUES (3, 'WATCHING');
INSERT INTO `MyMovieList`.`status` (`id`, `name`) VALUES (4, 'PLAN_TO_WATCH');
INSERT INTO `MyMovieList`.`status` (`id`, `name`) VALUES (5, 'DROPPED');

COMMIT;

